[[task]]
name = "Shopping"
desc = """
- Multiline description
- Much wow
"""
url = "https://www.google.co.uk/"
created = 1979-05-27T07:13:00Z
deadline = 2017-01-27T08:21:00Z

[[task]]
name = "Dishes"
desc = """
- Fill water
- Add washing up liquid
"""
url = "https://www.washingup.co.uk/"
created = 2016-01-27T15:44:12Z
deadline = 2017-06-27T08:24:02Z

[[task]]
name = "Write some Go"
desc = """
- Learn basics
- Write so programs
- Have fun
"""
url = "http://www.golang.org/"
created = 1994-05-27T07:35:02Z
deadline = 2016-05-27T07:32:00Z
